from dataclasses import dataclass
from typing import Optional


@dataclass
class Meta:
    name: str
    color: Optional[str]
    buying_price: int
    building_price: int = 0
    rent: int = 0
    rent_with_one_house: int = 0
    rent_with_two_houses: int = 0
    rent_with_three_houses: int = 0
    rent_with_four_houses: int = 0
    rent_with_hotel: int = 0


_spaces = [
    Meta(
        name="Go",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Mediterranean Avenue",
        color="Brown",
        buying_price=60,
        building_price=50,
        rent=2,
        rent_with_one_house=10,
        rent_with_two_houses=30,
        rent_with_three_houses=90,
        rent_with_four_houses=160,
        rent_with_hotel=250,
    ),
    Meta(
        name="Community Chest",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Baltic Avenue",
        color="Brown",
        buying_price=60,
        building_price=50,
        rent=4,
        rent_with_one_house=20,
        rent_with_two_houses=60,
        rent_with_three_houses=180,
        rent_with_four_houses=320,
        rent_with_hotel=450,
    ),
    Meta(
        name="Income Tax",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Reading Railroad",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Oriental Avenue",
        color="Light Blue",
        buying_price=100,
        building_price=50,
        rent=6,
        rent_with_one_house=30,
        rent_with_two_houses=90,
        rent_with_three_houses=270,
        rent_with_four_houses=400,
        rent_with_hotel=550,
    ),
    Meta(
        name="Chance",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Vermont Avenue",
        color="Light Blue",
        buying_price=100,
        building_price=50,
        rent=6,
        rent_with_one_house=30,
        rent_with_two_houses=90,
        rent_with_three_houses=270,
        rent_with_four_houses=400,
        rent_with_hotel=550,
    ),
    Meta(
        name="Connecticut Avenue",
        color="Light Blue",
        buying_price=120,
        building_price=50,
        rent=8,
        rent_with_one_house=40,
        rent_with_two_houses=100,
        rent_with_three_houses=300,
        rent_with_four_houses=450,
        rent_with_hotel=600,
    ),
    Meta(
        name="Jail / Just Visiting",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="St. Charles Place",
        color="Pink",
        buying_price=140,
        building_price=100,
        rent=10,
        rent_with_one_house=50,
        rent_with_two_houses=150,
        rent_with_three_houses=450,
        rent_with_four_houses=625,
        rent_with_hotel=750,
    ),
    Meta(
        name="Electric Company",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="States Avenue",
        color="Pink",
        buying_price=140,
        building_price=100,
        rent=10,
        rent_with_one_house=50,
        rent_with_two_houses=150,
        rent_with_three_houses=450,
        rent_with_four_houses=625,
        rent_with_hotel=750,
    ),
    Meta(
        name="Virginia Avenue",
        color="Pink",
        buying_price=160,
        building_price=100,
        rent=12,
        rent_with_one_house=60,
        rent_with_two_houses=180,
        rent_with_three_houses=500,
        rent_with_four_houses=700,
        rent_with_hotel=900,
    ),
    Meta(
        name="Pennsylvania Railroad",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="St. James Place",
        color="Orange",
        buying_price=180,
        building_price=100,
        rent=14,
        rent_with_one_house=70,
        rent_with_two_houses=200,
        rent_with_three_houses=550,
        rent_with_four_houses=750,
        rent_with_hotel=950,
    ),
    Meta(
        name="Community Chest",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Tennessee Avenue",
        color="Orange",
        buying_price=180,
        building_price=100,
        rent=14,
        rent_with_one_house=70,
        rent_with_two_houses=200,
        rent_with_three_houses=550,
        rent_with_four_houses=750,
        rent_with_hotel=950,
    ),
    Meta(
        name="New York Avenue",
        color="Orange",
        buying_price=200,
        building_price=100,
        rent=16,
        rent_with_one_house=80,
        rent_with_two_houses=220,
        rent_with_three_houses=600,
        rent_with_four_houses=800,
        rent_with_hotel=1000,
    ),
    Meta(
        name="Free Parking",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Kentucky Avenue",
        color="Red",
        buying_price=220,
        building_price=150,
        rent=18,
        rent_with_one_house=90,
        rent_with_two_houses=250,
        rent_with_three_houses=700,
        rent_with_four_houses=875,
        rent_with_hotel=1050,
    ),
    Meta(
        name="Chance",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Indiana Avenue",
        color="Red",
        buying_price=220,
        building_price=150,
        rent=18,
        rent_with_one_house=90,
        rent_with_two_houses=250,
        rent_with_three_houses=700,
        rent_with_four_houses=875,
        rent_with_hotel=1050,
    ),
    Meta(
        name="Illinois Avenue",
        color="Red",
        buying_price=240,
        building_price=150,
        rent=20,
        rent_with_one_house=100,
        rent_with_two_houses=300,
        rent_with_three_houses=750,
        rent_with_four_houses=925,
        rent_with_hotel=1100,
    ),
    Meta(
        name="B. & O. Railroad",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Atlantic Avenue",
        color="Yellow",
        buying_price=260,
        building_price=150,
        rent=22,
        rent_with_one_house=110,
        rent_with_two_houses=330,
        rent_with_three_houses=800,
        rent_with_four_houses=975,
        rent_with_hotel=1150,
    ),
    Meta(
        name="Ventnor Avenue",
        color="Yellow",
        buying_price=260,
        building_price=150,
        rent=22,
        rent_with_one_house=110,
        rent_with_two_houses=330,
        rent_with_three_houses=800,
        rent_with_four_houses=975,
        rent_with_hotel=1150,
    ),
    Meta(
        name="Waterworks",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Marvin Gardens",
        color="Yellow",
        buying_price=280,
        building_price=200,
        rent=24,
        rent_with_one_house=120,
        rent_with_two_houses=360,
        rent_with_three_houses=850,
        rent_with_four_houses=1025,
        rent_with_hotel=1200,
    ),
    Meta(
        name="Go To Jail",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Pacific Avenue",
        color="Green",
        buying_price=300,
        building_price=200,
        rent=26,
        rent_with_one_house=130,
        rent_with_two_houses=390,
        rent_with_three_houses=900,
        rent_with_four_houses=1100,
        rent_with_hotel=1275,
    ),
    Meta(
        name="North Carolina Avenue",
        color="Green",
        buying_price=300,
        building_price=200,
        rent=26,
        rent_with_one_house=130,
        rent_with_two_houses=390,
        rent_with_three_houses=900,
        rent_with_four_houses=1100,
        rent_with_hotel=1275,
    ),
    Meta(
        name="Community Chest",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Pennsylvania Avenue",
        color="Green",
        buying_price=320,
        building_price=200,
        rent=28,
        rent_with_one_house=150,
        rent_with_two_houses=450,
        rent_with_three_houses=1000,
        rent_with_four_houses=1200,
        rent_with_hotel=1400,
    ),
    Meta(
        name="Short Line",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Chance",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Park Place",
        color="Dark Blue",
        buying_price=350,
        building_price=200,
        rent=35,
        rent_with_one_house=175,
        rent_with_two_houses=500,
        rent_with_three_houses=1100,
        rent_with_four_houses=1300,
        rent_with_hotel=1500,
    ),
    Meta(
        name="Luxury Tax",
        color=None,
        buying_price=0,
        building_price=0,
        rent=0,
        rent_with_one_house=0,
        rent_with_two_houses=0,
        rent_with_three_houses=0,
        rent_with_four_houses=0,
        rent_with_hotel=0,
    ),
    Meta(
        name="Boardwalk",
        color="Dark Blue",
        buying_price=400,
        building_price=200,
        rent=50,
        rent_with_one_house=200,
        rent_with_two_houses=600,
        rent_with_three_houses=1400,
        rent_with_four_houses=1700,
        rent_with_hotel=2000,
    ),
]


def board() -> list:
    return _spaces


def name(space: int) -> str:
    return _spaces[space].name


# Individual spaces
GO = 0
JAIL = next(
    i for i, space in enumerate(_spaces) if space.name == "Jail / Just Visiting"
)
GO_TO_JAIL = next(i for i, space in enumerate(_spaces) if space.name == "Go To Jail")
INCOME_TAX = next(i for i, space in enumerate(_spaces) if space.name == "Income Tax")
COMMUNITY_CHEST = next(
    i for i, space in enumerate(_spaces) if space.name == "Community Chest"
)

# Groups
CHANCES = (i for i, space in enumerate(_spaces) if space.name == "Chance")
